### ISSUE TITLE
input sanitization

### ISSUE THREAD

**Issue by eroux** [BuddhistDigitalResourceCenter/lds-pdi#1]
While we're in sanitation, I thought it would be helpful to open this issue, first to create a precedent so that other issues may be open, second to indicate that there should be some tests of input sanitation to prevent [SPARQL injection](https://xkcd.com/327/). Even though I'm not sure the problem is really that bad, it's certainly a problem and it's a good exercise...

**Comment by MarcAgate** [comment]
I added a PreparedQuery class that allows for query parameters to be adjusted in any way we want. That's where sanitization can occur. We have now to define sanitization rules (i.e unwanted characters).
I found this very interesting :  http://www.morelab.deusto.es/code_injection/

**Comment by eroux** [comment]
Interesting! Can you make a few tests? I know SQL injection a little bit so I'll complete them with the patterns I know...

**Comment by MarcAgate** [comment]
Implemented in commit 8546a1b
