### ISSUE TITLE
remove lds-pdi context

### ISSUE THREAD

**Issue by eroux** [BuddhistDigitalResourceCenter/lds-pdi#10]
Instead of having the jsps on `/` and the REST interfaces on `/lds-pdi/`, the jsps should be on `/demo/` and the REST interface on the `/`.

**Comment by MarcAgate** [comment]
Done. Rest is on root path but follow the ontology IRI (i.e. it's serving P1583 at purl.bdrc.io:13280/resource/P1583) - any additional IRI can be implemented as well.
