### ISSUE TITLE
http://purl.bdrc.io/lib/workAllAssociations unreachable

### ISSUE THREAD

**Issue by berger-n** [BuddhistDigitalResourceCenter/lds-pdi#100]
http://purl.bdrc.io/lib/workAllAssociations?I_LIM=500&R_RES=bdr%3AW19740 returns error 404 with message `No graph template was found for the given path >>workAllAssociations`

**Comment by eroux** [comment]
things seem to be in order now

**Comment by berger-n** [comment]
thanks!
