### ISSUE TITLE
difference between rootSearchGraph & personFacetGraph results

### ISSUE THREAD

**Issue by berger-n** [BuddhistDigitalResourceCenter/lds-pdi#102]
http://purl.bdrc.io/lib/rootSearchGraph?LG_NAME=zh-x-phon-en&I_LIM=500&L_NAME=%22zhu%20fonian%22
returns one person but 
http://purl.bdrc.io/lib/personFacetGraph?LG_NAME=zh-x-phon-en&I_LIM=500&L_NAME=%22zhu%20fonian%22
returns none

**Comment by MarcAgate** [comment]
Fixed in commit https://github.com/BuddhistDigitalResourceCenter/lds-queries/commit/10aaf71acd17b4a7d81885625ae758a403adf88f
