### ISSUE TITLE
server error on some queries

### ISSUE THREAD

**Issue by eroux** [BuddhistDigitalResourceCenter/lds-pdi#105]
http://purl.bdrc.io/lib/rootSearchGraph?LG_NAME=sa-x-ndia&I_LIM=500&L_NAME=%22manju%22 fails with a 500 error

**Comment by eroux** [comment]
If I can have a little help on that, that would be helpful: I've added a `log.trace` in the lds-pdi code, but I cannot find a way to have tomcat log it... I added

```
log4j.logger.io.bdrc=TRACE
```

in `tomcat/webapps/ROOT/ldspdi.properties` and `tomcat/conf/logging.properties` but got no success in printing the trace message...

**Comment by MarcAgate** [comment]
It looks like this one has been fixed somehow...

**Comment by eroux** [comment]
yes, I think it was an analyzer issue, it's gone with the new configuration
