### ISSUE TITLE
JSON API for queries

### ISSUE THREAD

**Issue by eroux** [BuddhistDigitalResourceCenter/lds-pdi#11]
It would be interesting to have a REST JSON API for the queries (using [these concepts](http://www.vinaysahni.com/best-practices-for-a-pragmatic-restful-api)). It could list the queries when going on `/query/`, then a description of the query `ABC` on `/query/ABC` (the arguments, results, etc.), then another url (which one?) for running the query

**Comment by MarcAgate** [comment]
see http://buda1.bdrc.io/queries for a json list of the query templates
and (for instance)
see http://buda1.bdrc.io/queries/Topic_byAllNames.arq  for a json description of the templates, including the demo link

Note the actual usage of the query template using GET/POST/POST JSON is already implemented in the main query template service. Ex:

http://buda1.bdrc.io/resource/templates?searchType=Topic_byAllNames&L_NAME=rgyud (GET)

curl --data "searchType=Res_byName&L_NAME=(\"mkhan chen\" AND (\"'od zer\" OR \"ye shes\"))&LG_NAME=bo-x-ewts&I_LIM=100" http://localhost:8080/resource/templates (POST)

curl -H "Content-Type: application/json" -X POST -d @test.json http://localhost:8080/resource/templates (POST JSON)

**Comment by eroux** [comment]
(as a general observation, it tends to be perceived as rude to close an item opened by someone else, the usual protocol is to ask the person who opened the issue if it's ok to be closed)

Looks good! A few remarks:

- instead of `name`, maybe `id` could be used? Also, maybe it could include the `public/` part?
- the `.arq` part of the name/id is not used consistently and should never appear (I think)
- the different return variables and their meaning should be described (in your example it should be clear that it gives 1 column, named "?ID" which is the ID of the resource and which is a url
- `queryParams` should make clear that there are in fact two params, `L_NAME` and `LT_NAME`
- what is the point of the `queryString` field? It seems quite gratuitous...

**Comment by MarcAgate** [comment]
I think it's all done now (since commit 23bd0f1)

**Comment by eroux** [comment]
Ok, I'll open a separate issue for the remaining issues
