### ISSUE TITLE
is the "@" convention in lang tag necessary?

### ISSUE THREAD

**Issue by xristy** [BuddhistDigitalResourceCenter/lds-pdi#16]
is the convention you've used like: 

    ?L_TITLE?L_TITLELANG

necessary or if I want to, can I write:

    ?L_TITLE@?L_TITLELANG

?

**Comment by MarcAgate** [comment]
Hi Chris,
You must use ?L_TITLE?L_TITLELANG with (for instance) L_TITLELANG=@bo-x
-ewts
the @ parameter cannot be part of the template because it is considered
as a Threat by the InjectionTracker.
Marc

Le jeudi 01 février 2018 à 07:52 -0800, Chris Tomlinson a écrit :

**Comment by xristy** [comment]
I guess it would be good to clarify the injection threat. Links to discussion?

Maybe we could have `?T_TITLE` with the meaning that a valid language tag must be provided and permit writing

    ?L_TITLE@?T_TITLE

Rather than another issue, is the use of all caps for template variables part of the code or is the set of template variables determined by:

    #QueryParams=

so that one might write:

    #QueryParams=l_name,l_lang,i_lim

**Comment by MarcAgate** [comment]
Could you tell me more about the issue coming from using ?L_TITLE?L_TITLELANG  ?  

Regarding @ viewed as an Injection threat, it is the way the ParameterizedSparqlString class works (it just refuses @  in the query (it might even be sparql itself since it uses the lang function - I have to check).
 (http://jena.apache.org/documentation/javadoc/arq/org/apache/jena/query/ParameterizedSparqlString.html).

**Comment by eroux** [comment]
Well, I see that [currently](https://github.com/BuddhistDigitalResourceCenter/lds-pdi/blob/2d986f54619b90eb6c785eaefd18447810e66c45/src/main/java/io/bdrc/ldspdi/sparql/InjectionTracker.java#L58) we're not using the lang tags in a proper way. It seems to me that having the following mechanism would be more logical:

- we would have a convention saying that `?ls_foo` is a lang string (and not just any literal like `l_foo`)
- we would use `setLiteral(int index, String value, String lang)` (with the final lang argument)
- we would have a convention that in order to fill `?ls_foo` we would have `s_foo=xxx&lt_foo=yyy`
- we would validate the lang tag with a BCP-47 validation mechanism

wdyt?

**Comment by xristy** [comment]
The user documentation for [Parameterized SPARQL String](https://jena.apache.org/documentation/query/parameterized-sparql-strings.html) is also useful.

It appears that the answer to my question about whether we could use lower-case versus upper case param names should be YES since those names are under our control and not required by `ParameterizedSparqlString`. You're using the `L_`, `I_` and `R_` as conventions to determine when to use `setLiteral` and so on - which seems fine and using a case-insensitive test would be easy.

As Élie points out the handling of language tags may not be quite correct, although as I understand the PSS, it doesn't check validity of the string resulting from substitution until `asQuery` is invoked. If this is the case then it seems that `@` should not be an issue in the string!? The "@" is apparently not being interpreted until `asQuery` (otherwise I don't see how current queries are working).

Élie's proposal is sound in terms of permitting some validation of language tags which seems beneficial.

**Comment by xristy** [comment]
`setLiteral(String var, String value, String lang)` would presumably be the form to use, rather than the positional version.

I assume that the

    #QueryParams=....

is used to validate that the params supplied in the request are the ones the template is designed to accept.

**Comment by MarcAgate** [comment]
Right, #QuertParams is used for validation against templated request. Obviously there is no restriction regarding params case: I suggested upper case for a better readability of the templates : that matters quite a bit when you are designing query templates.
I agree we are not correctly setting up languages in templates. I am going to implement you solution and I hope jena;text will be fine with it.
I am not sure that setLiteral(?S_NAME, "whatever", LT_NAME) applied to text:query ( ?S_NAME), will produce the expected jena:text/lucene syntax. I must test that first

Regarding the BCP-47 thing I will use Locale (https://docs.oracle.com/javase/8/docs/api/java/util/Locale.html)

**Comment by MarcAgate** [comment]
Just tested the produced query syntax and everything's fine.

**Comment by xristy** [comment]
> Obviously there is no restriction regarding params case.

So you will be changing the [tests](https://github.com/BuddhistDigitalResourceCenter/lds-pdi/blob/2d986f54619b90eb6c785eaefd18447810e66c45/src/main/java/io/bdrc/ldspdi/sparql/InjectionTracker.java#L52) to allow arbitrary case?

**Comment by MarcAgate** [comment]
I would prefer to keep everything uppercase (even though you use have lower case params names with uppercase prefix). 
The very practical reason to that is readability (in particular when I look for params into a big non pretty json string, either in the browser or in the console - add &jsonOut=true to the url of any request of the index page and you'll understand my point). 
Moreover, once all the demo stuff will be gone, replaced by BLMP, we will be the only ones to see these strings, most likely for debugging or new development.

**Comment by eroux** [comment]
About the test for bcp-47 I think it makes sense to keep things generic and use the Locale method, if users are looking for strings in Klingon they won't find any but that shouldn't bother the sparql query engine...

**Comment by xristy** [comment]
You may keep what you write in upper case of course; however, the template author should have the  freedom to choose. The editing/authoring facility will still present a query with template variables to the author and it is a matter-of-taste as to whether the all uppercase. mixed case, or lower case work for the person authoring the template. The underlying tool should be flexible rather than rigid.

**Comment by xristy** [comment]
How will the `Locale` class be used as far as user input of language tags? If tags are being validated then won't it be helpful to have at least a list of BUDA private-use-case extensions?

**Comment by eroux** [comment]
The `Locale` class can validate if a lang tag is a real lang tag (and not some SPARQL injection or whatever), that's all lds should do IMO. If we have a list of lang tags inside the lds, that means redeploying each time we change or add a language, or having a complex mechanism for that, I don't think it's necessary... in the UI, of course, users will choose in a predefined list, but that would be on another level... wdyt?

**Comment by MarcAgate** [comment]
I used the Locale.Builder class for BCP 47 validation in InjectionTracker.
Regarding lang settings in query templates, the convention is as follows:
A langage specific request will use L_ prefixed params for the string to be searched and LG_ prefix to indicate the associated lang.

Ex: L_NAME="chos rgyal" LG_NAME=bo-x-ewts

or simply L_NAME="'od zer" with no corresponding LG_NAME param if the language is unspecified.
