### ISSUE TITLE
next link for pagination needs to be relative

### ISSUE THREAD

**Issue by xristy** [BuddhistDigitalResourceCenter/lds-pdi#17]
v0.4.4 is deployed on aws and when running [Res_byLabel](http://purl.bdrc.io/resource/templates?searchType=Res_byLabel&L_NAME=(%22mkhan+chen%22+AND+(%22%27od+zer%22+OR+%22ye+shes%22))&L_LANG=@bo-x-ewts&I_LIM=100) for example, the [next page link](http://localhost:13280/resource/templates?searchType=Res_byLabel&L_NAME=%28%22mkhan+chen%22+AND+%28%22%27od+zer%22+OR+%22ye+shes%22%29%29&L_LANG=%40bo-x-ewts&I_LIM=100&pageNumber=2&hash=686700044) is pointing at `localhost:13280` rather than the origin `host:port` 

Similarly for the [prev link](http://localhost:13280/resource/templates?searchType=Res_byLabel&L_NAME=%28%22mkhan+chen%22+AND+%28%22%27od+zer%22+OR+%22ye+shes%22%29%29&L_LANG=%40bo-x-ewts&I_LIM=100&pageNumber=1&hash=686700044).

**Comment by MarcAgate** [comment]
Fixed !
