### ISSUE TITLE
more elaborate arguments/result description

### ISSUE THREAD

**Issue by eroux** [BuddhistDigitalResourceCenter/lds-pdi#18]
It would be good to be able to elaborate on some aspects of the parameters in the template and JSON API, and also more info about the columns of the result, or if the result is a construct (which means valid RDF, not just SPARQL Results). see https://github.com/BuddhistDigitalResourceCenter/lds-pdi/issues/11#issuecomment-363117729 for some details. No need to do that right now.

**Comment by MarcAgate** [comment]
Implemented as of commit c3028fa.
I will take care of the following points in order to close the issue:
1) modify all templates so they can display their full metadata set
2) Write some documentation (query template design guidelines)
3) Provide a query template example (model)

**Comment by MarcAgate** [comment]
All done as of commit 179a47c

**Comment by MarcAgate** [comment]
Improved and finalized in commit f41a720
