### ISSUE TITLE
serving the whole ontology

### ISSUE THREAD

**Issue by eroux** [BuddhistDigitalResourceCenter/lds-pdi#19]
It would be good to serve the ontology in various serializations, probably on the URI it claims: `http://purl.bdrc.io/ontology/`. Unless it's already taken by the ontology service? Anyways, even if the ontology service is hooked here, it would be useful to make it display some links like hmmm... maybe `http://purl.bdrc.io/ontology.ttl`? This way the BLMP could just download it this way instead of having its own version.

**Comment by MarcAgate** [comment]
Done in last commit (dc287d8).
url is http://purl.bdrc.io/ontology.{ext} - See README for supported extensions

**Comment by MarcAgate** [comment]
Can we close this one ?

**Comment by eroux** [comment]
yep thanks!
