### ISSUE TITLE
possibility to query by actual URI (not local name)

### ISSUE THREAD

**Issue by eroux** [BuddhistDigitalResourceCenter/lds-pdi#22]
I think it would be helpful to allow users to query resources with their actual ID instead of [hardcoding the bdr: prefix](https://github.com/BuddhistDigitalResourceCenter/lds-pdi/blob/master/src/main/java/io/bdrc/ldspdi/sparql/InjectionTracker.java#L48). So the query would be

```json
{
  "R_RES": "http://purl.bdrc.io/resource/I29329_I001"
}
```

instead of `I29329_I001` in [this query](https://github.com/BuddhistDigitalResourceCenter/lds-queries/blob/master/public/IIIFPres_itemInfo.arq) (or maybe having some prefixes in the configuration so that `bdr:I29329_I001` works too?). It's not really an emergency but we want to allow federation in the future, which means dealing with URLs not in our usual zone.

(note that this would obviously not affect the `/resource` endpoint which would still serve urls like `http://purl.bdrc.io/resource/I29329_I001` and not `http://purl.bdrc.io/resource/bdr:I29329_I001`, nor the ontology endpoints)

**Comment by MarcAgate** [comment]
ldspdi now supports resource param of the form prefix:resourceID or full_URI/resource_ID.
The /resource endpoint remains as is.

**Comment by eroux** [comment]
looks good! I didn't test but let's close it, I'll reopen it if some bugs appear
