### ISSUE TITLE
cache configuration

### ISSUE THREAD

**Issue by eroux** [BuddhistDigitalResourceCenter/lds-pdi#24]
The [current cache configuration](https://github.com/BuddhistDigitalResourceCenter/lds-pdi/blob/master/src/main/resources/cache.ccf) is really overkill and I'm not sure it would work great (no `user.dir`), let's be reasonable and start with a config in memory only

**Comment by MarcAgate** [comment]
Fixed as of commit 4997c01

**Comment by eroux** [comment]
looks good, thanks!
