### ISSUE TITLE
webdefault.xml

### ISSUE THREAD

**Issue by eroux** [BuddhistDigitalResourceCenter/lds-pdi#25]
I'm wondering what the [webdefault.xml](https://github.com/BuddhistDigitalResourceCenter/lds-pdi/blob/master/src/main/webapp/WEB-INF/webdefault.xml) file is? It contains some strange things such as

```xml
<param-value>>true</param-value>
```

or

```xml
<param-value>/home/marc/lds-queries/</param-value>
```

**Comment by MarcAgate** [comment]
webdefault.xml is used by jetty for setting up global settings, mainly the fuseki service url and lds-queries dir path. 
```
<plugin>
            <groupId>org.eclipse.jetty</groupId>
            <artifactId>jetty-maven-plugin</artifactId>
            <version>9.4.7.RC0</version>
            <configuration>
	            <webApp>
                    <context-path>/</context-path>	            	                
		            <webInfIncludeJarPattern>^$</webInfIncludeJarPattern>
		            <containerIncludeJarPattern>^$</containerIncludeJarPattern> 
                    <defaultsDescriptor>src/main/webapp/WEB-INF/webdefault.xml</defaultsDescriptor>
	            </webApp>
                </configuration>                
         </plugin>
```
In short this is jetty support or the equivalent of context.xml in tomcat config.

**Comment by MarcAgate** [comment]
Could we close this one ?

**Comment by eroux** [comment]
Well, I'm still a bit puzzled by this file, mostly for lines 14 and 18 that are invalid xml, and for line 34 that contains a reference to `/home/marc/lds-queries/` which, I guess, is specific to your local installation. So we have two options:
- the file is broken but that doesn't matter as it's not really used and it can be removed
- the file is useful and should be fixed, but I still don't understand what its use is...?

**Comment by MarcAgate** [comment]
I fixed the typos in lines 14 and 18.
Actually, you're right since this file is not used in production. However, without it, one cannot get a local version running using mvn jetty:run. This local usage explains the presence of my local path.
If this file doesn't cause any trouble (and to my knowledge it doesn't), it might be practical to keep it in the git directory, so one can run the project immediatly after cloning it.

**Comment by eroux** [comment]
Well, if we change `/home/marc/lds-queries/` to something more reasonable why not, if relative path work and we can change it to `lds-queries/` then that would solve the issue for me.

**Comment by MarcAgate** [comment]
Let's go for that solution as we cannot know where the local lds-queries is.

**Comment by eroux** [comment]
thanks
