### ISSUE TITLE
submodules for queries

### ISSUE THREAD

**Issue by eroux** [BuddhistDigitalResourceCenter/lds-pdi#3]
It would be helpful to have the queries in their own git repository (`lds-queries` ?), with two directories:

- `public/` would be the queries regular users can execute
- `admin/` would be queries that only users with certain privileges can execute (no need for an auth mechanism right now, it's just preparing for the future)

Then lds-pdi could take as a parameter the path of a local `lds-queries` git repo and use that. lds-pdi would also have a mechanism to update the git repository when a users requests the url `/admin/update-lds-queries`. The idea of a submodule had been initially proposed, but I think it would actually make things a bit more difficult (not distributable through maven, cumbersome need of updating the referenced commit, possibility of annoying conflicts, etc.). The [jgit](https://www.eclipse.org/jgit/) library should be easy enough to use for that purpose (and is used in the migration)...

**Comment by MarcAgate** [comment]
A first version has been implemented. Somme kind of online query template editor along with online validation and testing functionalities should be created sooner or later.
