### ISSUE TITLE
ontology service should list individuals of the various types

### ISSUE THREAD

**Issue by eroux** [BuddhistDigitalResourceCenter/lds-pdi#32]
We should provide access to the various individuals of the different types of the ontology (subclasses of `:Type`)

**Comment by eroux** [comment]
the individuals are in the ontology graph, so it shouldn't be too hard to implement... it's a new top priority coming from above

**Comment by MarcAgate** [comment]
Implemented in commit 06640e9

**Comment by eroux** [comment]
Thanks, I think it would be more intellegible to display prefixes, as it's easy in the [current state](http://purl.bdrc.io/demo/ontology?classUri=http://purl.bdrc.io/ontology/core/AccessType) to believe that,  `AccessFairUse` is `:AccessFairUse` while it's in fact `bdr:AccessFairUse`

**Comment by MarcAgate** [comment]
Added in commit 502fce0

**Comment by eroux** [comment]
thanks!
