### ISSUE TITLE
POST version of the queries

### ISSUE THREAD

**Issue by eroux** [BuddhistDigitalResourceCenter/lds-pdi#4]
I don't know how smoothly Jersey allows that (IIRC it's quite simple), but users should be able to request the queries using POST and encoding their request in JSON.

**Comment by MarcAgate** [comment]
Json format is Default jena fuseki raw response format : https://www.w3.org/TR/rdf-sparql-json-res/
Run curl --data "searchType=pdi_w_bibli&L_NAME=chos+dbyings+bstod+pa" http://buda1.bdrc.io:13280/lds-pdi/query for an example

**Comment by eroux** [comment]
what about sending JSON in the POST request (as opposed to JSON being the returned format)?  This was the initial proposal of the ticket, something like:

```
curl -H "Content-Type: application/json" -X POST -d '{"searchType":"pdi_w_bibli","L_NAME":"chos dbyings bstod pa"}' http://buda1.bdrc.io:13280/lds-pdi/query 
```

**Comment by MarcAgate** [comment]
Done !
