### ISSUE TITLE
compressing results

### ISSUE THREAD

**Issue by eroux** [BuddhistDigitalResourceCenter/lds-pdi#40]
If I understand correctly, the current results are not compressed:

```
$ curl -I -H 'Accept-Encoding: gzip,deflate' http://purl.bdrc.io/resource/P1583.ttl

HTTP/1.1 200 OK
Server: nginx/1.10.3
Date: Thu, 08 Mar 2018 10:12:52 GMT
Content-Type: text/turtle;charset=utf-8
Content-Length: 6364
Connection: keep-alive
Access-Control-Allow-Origin: *
Access-Control-Allow-Headers: origin, content-type, accept, authorization
Access-Control-Allow-Credentials: true
Access-Control-Allow-Methods: GET, POST, PUT, DELETE, OPTIONS, HEAD
```

no sign of compression... there are some recipes (like [this one](http://www.codingpedia.org/ama/how-to-compress-responses-in-java-rest-api-with-gzip-and-jersey/) for that, it seems relatively easy but I have no experience with it.

**Comment by MarcAgate** [comment]
Implemented as of commit 222533f
