### ISSUE TITLE
improve prefixes in ttl output

### ISSUE THREAD

**Issue by eroux** [BuddhistDigitalResourceCenter/lds-pdi#41]
looking at [bdr:W0RIT00001](http://purl.bdrc.io/resource/W0RIT00001), a few things are not perfect:

- the `owl:` prefix is missing
- an `rkts:` prefix would be good, but we're not at a stage where it can be defined yet, the indicated URL will probably change in the future

Also, I'm thinking that because we're using a custom ttl serializer, we could make it output only prefixes that appear in the document. This seems like a reasonable improvement (I hope it's doable, not sure).

**Comment by MarcAgate** [comment]
The owl: prefix is present (it was probably added recently). 

I think there's a difference between serializing a Model resulting from a sparql query and a Model somehow built programmatically.

In the first case, it looks like prefixes are listed in fuseki config files. Therefore I doubt we can adjust the outputed prefixes to prefixes appearing in the doc without parsing the Model.

I don't see any application of the second case in our system.
