### ISSUE TITLE
improving Ontology synchronization

### ISSUE THREAD

**Issue by eroux** [BuddhistDigitalResourceCenter/lds-pdi#43]
There are a few things that should be improved in the ontology synchronization with git:
- [ ] the ontology (in its inferred version) should be transferred to Fuseki (in the appropriate graph with URI `bdo:ontologySchema`) when a new version is available
- [ ] the [webhook mechanism of Github](https://developer.github.com/webhooks/creating/) could be used to be notified of changes instead of polling

**Comment by MarcAgate** [comment]
I need credentials to set webhooks in owl-schema repository. (cannot see the settings menu with my current profile)

**Comment by eroux** [comment]
Thanks! Tell me the URL, I'll set it up

**Comment by MarcAgate** [comment]
Done
