### ISSUE TITLE
option to redirect html queries to resources

### ISSUE THREAD

**Issue by eroux** [BuddhistDigitalResourceCenter/lds-pdi#48]
From a user's perspective, it would be helpful to redirect some queries to the public digital library, for instance, under some circumstances, http://purl.bdrc.io/resource/W8LS19368 would be redirected to http://library.bdrc.io/show/bdr:W8LS19368 . The circumstances would be:
- html or xhtml accept header
- no accept header
- accept header not corresponding to a known RDF serialization

**Comment by MarcAgate** [comment]
Done
