### ISSUE TITLE
allow prefix decls in .arq files

### ISSUE THREAD

**Issue by xristy** [BuddhistDigitalResourceCenter/lds-pdi#50]
It would be helpful to allow prefix decls in .arq files instead of either having to add seldom used or experimental prefixes to the common prefixes.txt file or requiring fully spelled out uris in the arq files

**Comment by eroux** [comment]
I've used that in a [query](https://github.com/BuddhistDigitalResourceCenter/lds-queries/blob/master/public/IIIFPres_workGraph.arq), it seems to work fine...

**Comment by xristy** [comment]
great to know!
