### ISSUE TITLE
http code 406 when unavailable encoding 

### ISSUE THREAD

**Issue by eroux** [BuddhistDigitalResourceCenter/lds-pdi#54]
When a resource is asked with an `Accept` header that we don't serve, I think we should return an [http 406](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/406)

**Comment by MarcAgate** [comment]
This was implemented for POST/GET methods for the following endpoints:

-@Path("/resource/{res}") 
-@Path("/resource/{res}.{ext}") 
in the second case, the extension is converted to mimeType in order to do the checking.

**Comment by eroux** [comment]
thanks, it's interesting to have done that for the second case... I think 404 was fine, but why not!

**Comment by eroux** [comment]
Nope:

```
$ curl -I http://purl.bdrc.io/resource/P1583 -H "Accept: text/invalid"

HTTP/1.1 300 Multiple Choices
```

please make a unit test for this case

**Comment by MarcAgate** [comment]
Well, this is how we implemented it in GET method (returning a the content location of a html page containing possible urls for the requested resouce) . 
406 is only returned for POST method

**Comment by eroux** [comment]
The behavior is correct for post, but for get it should be 406 except when the accept header is empty, in which case it should be 300. (It used to be this way, but there were some problems during the manual merge of the code I wrote I think)

**Comment by eroux** [comment]
Thanks, I think the code I wrote took less lines:

https://github.com/BuddhistDigitalResourceCenter/lds-pdi/blob/testVariants/src/main/java/io/bdrc/ldspdi/rest/resources/PublicDataResource.java#L129

but I'm probably being picky...

**Comment by eroux** [comment]
great! cool to see some unit tests!
