### ISSUE TITLE
http 300 when no accept header

### ISSUE THREAD

**Issue by eroux** [BuddhistDigitalResourceCenter/lds-pdi#55]
This doesn't answer any real life problem I think, but it may be helpful to implement in order to have a nice demo:

When a user would go to `http://purl.bdrc.io/resource/XXX` with no `Accept` header, a [http 300](https://developer.mozilla.org/fr/docs/Web/HTTP/Status/300) code should be returned with the list of rdf serializations and the link to the html page. I think [this example](https://www.w3.org/Style/Examples/007/figures.ht) is ok...

Note that because browser ask for html, this won't affect regular users.

**Comment by eroux** [comment]
I think in this case we should have the list of alternates as in #63 but also the `TCN` header set to `list` (if I look at the examples of [rfc2295](https://www.ietf.org/rfc/rfc2295.txt))

**Comment by MarcAgate** [comment]
Implemented as of commit 2b33cc2

To be tested with:
`curl -v http://localhost:8080/resource/P88  -H "Accept:"`
and
`curl -v -X POST http://localhost:8080/resource/P88  -H "Accept:"`
