### ISSUE TITLE
ttl link to resources

### ISSUE THREAD

**Issue by eroux** [BuddhistDigitalResourceCenter/lds-pdi#57]
in the html interface, it would be convenient that when we have a link to a resource in ttl (in parenthesis), for instance on

http://buda1.bdrc.io/query/IIIFPres_itemInfo?R_RES=bdr:I29329

we could have

```
W29329 (ttl)
```

with html

```
<a href="http://purl.bdrc.io/resource/W29329" target="_blank">W29329</a> (<a href="http://purl.bdrc.io/resource/W29329.ttl">W29329</a>)
```

**Comment by MarcAgate** [comment]
Done as of commit 5a7c048
