### ISSUE TITLE
use query in lds-query for describing the resource

### ISSUE THREAD

**Issue by eroux** [BuddhistDigitalResourceCenter/lds-pdi#71]
Instead of having the query hardcoded ([here](https://github.com/BuddhistDigitalResourceCenter/lds-pdi/blob/master/src/main/java/io/bdrc/ldspdi/sparql/QueryProcessor.java#L53)), there should be a way to get it from lds-query and parametrize it with injection prevention mechanisms, like any other query. One of the reasons (besides injection prevention) is that for etexts we may want a small variantion

**Comment by MarcAgate** [comment]
Implemented as of commit 5126e93 using new queryFileParser/Tracker

**Comment by eroux** [comment]
sure, there should be a static set of query files in `src/test/resources/arq/` that should be used in the tests

**Comment by MarcAgate** [comment]
ServiceConfig.initForTest() is now updating the templates in a local git dir for test purpose, from lds-queries repo.
queryPath for test is taken from lds-pdi.properties  (it's ./lds-queries/ )

**Comment by eroux** [comment]
I don't think it's a good idea... tests shouldn't depend on lds-queries, they should be self-contained, I still think a static set of query files in `src/test/resources/arq/` would be better... they don't need to use git or anything

**Comment by MarcAgate** [comment]
All of these points have been addressed since commit ce9f7e6

**Comment by eroux** [comment]
thanks!
