### ISSUE TITLE
link to data version of results in html pages of queries

### ISSUE THREAD

**Issue by eroux** [BuddhistDigitalResourceCenter/lds-pdi#83]
For instance on [this page](http://purl.bdrc.io/query/Person_allNames?L_NAME=klu+sgrub), it would be useful to have a link to json or csv

**Comment by MarcAgate** [comment]
done as of commit 65afbf3

**Comment by MarcAgate** [comment]
Can we close this one ? http://purl.bdrc.io/query/Person_allNames?L_NAME=klu+sgrub

**Comment by eroux** [comment]
Almost, can we add a link to the simple CSV version? like 

```
Other formats: Json / CSV / Simple CSV
```

**Comment by MarcAgate** [comment]
Done as of commit 2006198

**Comment by eroux** [comment]
thanks!
