### ISSUE TITLE
Etag and last modification date for resources

### ISSUE THREAD

**Issue by eroux** [BuddhistDigitalResourceCenter/lds-pdi#84]
git-to-dbs [adds](https://github.com/BuddhistDigitalResourceCenter/git-to-dbs/blob/master/src/main/java/io/bdrc/gittodbs/FusekiHelpers.java#L74) some properties to each named graphs indicating the commit, and the modification date could be added. These properties should be used by the `resource/` endpoint, and also the same mechanism could be used for the auth endpoints.

**Comment by MarcAgate** [comment]
Done as of commit 0702747
Etag are set with gitRevision # for /resource endpoints
Last-Modified is set to the last update time of RdfAuthModel in /auth endpoints
