### ISSUE TITLE
getting query results in json

### ISSUE THREAD

**Issue by eroux** [BuddhistDigitalResourceCenter/lds-pdi#88]
I can't find a way to get the query results in json, it should be documented somwhere either in the results, in the doc or in the code. I tried

http://purl.bdrc.io/query/volumesForWork?R_RES=bdr:W23703&format=jsonld

and

```
curl -H "Accept: application/ld+json" http://purl.bdrc.io/query/volumesForWork?R_RES=bdr:W23703
```

with no success

**Comment by MarcAgate** [comment]
The query format is as follows:

http://purl.bdrc.io/query/volumesForWork?R_RES=bdr:W23703&jsonOut

It was indicated in README (it's now written in bold ! )

**Comment by eroux** [comment]
I think it should be indicated on http://purl.bdrc.io/
