### ISSUE TITLE
rootSearchGraph query failing when searching in English

### ISSUE THREAD

**Issue by berger-n** [BuddhistDigitalResourceCenter/lds-pdi#93]
in English it fails:
http://purl.bdrc.io/lib/rootSearchGraph?LG_NAME=en&I_LIM=500&L_NAME=%22shantideva%22

error message is `type in RootResults.getResultsMap(Model mod) >> http://wikiba.se/ontology-beta#Item`

whereas in Tibetan it is ok : 
http://purl.bdrc.io/lib/rootSearchGraph?LG_NAME=bo-x-ewts&I_LIM=500&L_NAME=%22shantideva%22

**Comment by berger-n** [comment]
another query failing: 
http://purl.bdrc.io/lib/rootSearchGraph?LG_NAME=bo-x-ewts&I_LIM=500&L_NAME=%22%27dul%20ba%20ka%22
not in English though
but error seems related: `type in RootResults.getResultsMap(Model mod) >> http://purl.bdrc.io/ontology/core/Etext`

**Comment by eroux** [comment]
I believe this is fixed, superseded by #103

**Comment by berger-n** [comment]
it is
thanks!
