### ISSUE TITLE
error retrieving annotation collection when adding Prefer field to header

### ISSUE THREAD

**Issue by berger-n** [BuddhistDigitalResourceCenter/lds-pdi#94]
when fetching annotation collection content in terminal this works:
```
curl http://purl.bdrc.io/anncollection/ANCWCBC2237_C001 
-H "Accept: application/json" 
-H 'Prefer: return=representation;include="http://www.w3.org/ns/oa#PreferContainedDescriptions"'
```

but in javascript it fails when using ``prefer`` in header:
``Failed to load http://purl.bdrc.io/anncollection/ANCWCBC2237_C002: Request header field prefer is not allowed by Access-Control-Allow-Headers in preflight response.``

whereas without ``prefer`` in header it works

**Comment by eroux** [comment]
can you try with latest version? (I just deployed it)

**Comment by berger-n** [comment]
seems to be working fine
thanks!

![image](https://user-images.githubusercontent.com/33383857/46352094-3e098380-c659-11e8-9460-fd98863df73d.png)

**Comment by eroux** [comment]
ok thanks!
