### ISSUE TITLE
purl.bdrc.io/ontology/core/Person.ttl etc fail

### ISSUE THREAD

**Issue by xristy** [BuddhistDigitalResourceCenter/lds-pdi#95]
References to ontology items requesting ttl, rdf, and json (others?) fail. E.g., [Person.ttl](http://purl.bdrc.io/ontology/core/Person.ttl) and [workHasItem.json](http://purl.bdrc.io/ontology/core/workHasItem.json) return error info:

    {"status":404,"code":5020,"message":"http://purl.bdrc.io/ontology/core/Person.ttl","link":null,"developerMessage":null}
    {"status":404,"code":5020,"message":"http://purl.bdrc.io/ontology/core/workHasItem.json","link":null,"developerMessage":null}

On the other hand without any affix an html view is returned, like: [Person](http://purl.bdrc.io/ontology/core/Person)

But  [Person.html](http://purl.bdrc.io/ontology/core/Person.html) fails; whereas, [P314.html](http://purl.bdrc.io/resource/P314.html) returns a list of possible affixes which does not include _html_. 

Shouldn't _html_ be equivalent to no affix?

**Comment by eroux** [comment]
I think it should be working fine now

**Comment by xristy** [comment]
Looks good.
