### ISSUE TITLE
topic Tree having counts equal to -1

### ISSUE THREAD

**Issue by berger-n** [BuddhistDigitalResourceCenter/lds-pdi#99]
query http://purl.bdrc.io/lib/workFacetGraph?LG_NAME=en&I_LIM=500&L_NAME=%22%27od%20zer%22 returns a tree having some topics with count equal to -1: 
![image](https://user-images.githubusercontent.com/33383857/46524116-12201500-c888-11e8-8e2c-e8992f9ff5ac.png)

**Comment by MarcAgate** [comment]
Fixed as of commit cbe74a6 . the count node is actually the number of sub-categories in the tree for a given Taxonomy/Topic. We had count=-1 in the previous implementation for all leaves of the tree, (-1 being the default value). **In this implementation, there is (logically) no count node for the leaves of the Tree.**

**Comment by berger-n** [comment]
I'm not sure what you mean here...
let's take a look at this brand new data http://library.bdrc.io/search?q=%22manjusri%22&lg=sa-x-ndia&t=Work for a change
![image](https://user-images.githubusercontent.com/33383857/47100132-190b3800-d237-11e8-859f-c44e7f9373c7.png)
aren't the numbers supposed to tell user how many works there are in given topic/subtopic ?

**Comment by MarcAgate** [comment]
Right, my mistake ! And the -1 issue occurs only on each leave of the Taxonomy Tree. More to come...

**Comment by MarcAgate** [comment]
Fixed !
